### PR TITLE
Fix #4407 - Minecraft doesn't crash anymore when gate sets filler pattern

### LINKED ISSUE #4407: Crash with gate trying to set filler pattern
BuildCraft version: 7.99.24.1
Forge version: 14.23.5.2837
Link to crash report or log: https://gist.github.com/128-bit-guy/5e5b9706bfd9925fe9c02674ae44e276
Singleplayer or multiplayer: singleplayer
Steps to reproduce:
1) Place filler
2) Place pipe
3) Add gate to pipe
4) Set gate action to set filler pattern
5) Activate gate

### PR DESCRIPTION
**Pull request by 128-bit-guy**
Game doesn't crash anymore, when gate sets filler pattern

### CODE REVIEW

File: common/buildcraft/builders/tile/TileFiller.java [hunk 1]
```diff
@@ -496,7 +496,7 @@ public IBox getBox() {
     @Override
     public void setPattern(IFillerPattern pattern, IStatementParameter[] params) {
         patternStatement.set(pattern);
-        IntStream.range(0, patternStatement.maxParams).forEach(i -> patternStatement.set(i, params[i]));
+        IntStream.range(0, params.length).forEach(i -> patternStatement.set(i, params[i]));
```
Comment (AlexIIL) [inline common/buildcraft/builders/tile/TileFiller.java]: Should this be `Math.min(params.length, patternStatement.maxParams)` instead?

Comment (AlexIIL) [reply common/buildcraft/builders/tile/TileFiller.java]: Actually never mind - I've noticed a few other places where this was wrong so I'll fix those too.

Comment (128-bit-guy) [reply common/buildcraft/builders/tile/TileFiller.java]: I don't think, that it should, because filler action won't have more parameters, than patternStatement.maxParamenters.

Comment (AlexIIL) [reply common/buildcraft/builders/tile/TileFiller.java]: Technically the params array comes from the gate length, not the filler action's maximum number of parameters. (However buildcraft itself doesn't have any gates with more than 3 paramaters so this shouldn't actually ever happen)
