### PR TITLE
Fixed facades returning BlockFaceShape.UNDEFINED when they shouldn't

### LINKED ISSUE #3994: [1.12.2] [PIPES] getBlockFaceShape() always returns BlockFaceShape.SOLID
I found this while testing https://github.com/MinecraftForge/MinecraftForge/pull/4680. The PR fixes an inconsistency between vanilla glass and modded glass. This is done by checking if the block face that's against the water block is solid, however Buildcraft pipes always return `BlockFaceShape.SOLID` even without a facade.

Also tested with the version here on github and the issue changed to some returning `BlockFaceShape.UNDEFINED` when they shouldn't (i.e. Glass facade), seems to have changed because of the `getBlockFaceShape()` override on  https://github.com/BuildCraft/BuildCraft/commit/8aa06a8901b75d20aea5fd587dad6b0ac46a47de.

BuildCraft version: 7.99.14
Forge version:
Link to crash report or log: 
Singleplayer or multiplayer: Both
Additional information:

### PR DESCRIPTION
**Pull request by Managarmr719**
Fixes https://github.com/BuildCraft/BuildCraft/issues/3994.

Also changed hollow facades to be considered as not solid.

### CODE REVIEW

File: common/buildcraft/transport/plug/PluggableFacade.java [hunk 1]
```diff
@@ -47,14 +47,14 @@
...
-        isSideSolid = states.areAllStatesSolid(side);
+        isSideSolid = states.areAllStatesSolid(side) && !states.phasedStates[activeState].isHollow();
     }
 
     public PluggableFacade(PluggableDefinition def, IPipeHolder holder, EnumFacing side, NBTTagCompound nbt) {
         super(def, holder, side);
         this.states = FacadeInstance.readFromNbt(nbt, "states");
         activeState = MathUtil.clamp(nbt.getInteger("activeState"), 0, states.phasedStates.length - 1);
-        isSideSolid = states.areAllStatesSolid(side);
+        isSideSolid = states.areAllStatesSolid(side) && !states.phasedStates[activeState].isHollow();
```
Comment (AlexIIL) [inline common/buildcraft/transport/plug/PluggableFacade.java]: activeState can change at *any* time. Depending on it here doesn't make much sense.

Honestly neither does allowing phasing between hollow and non-hollow facades. As they aren't implemented yet this hasn't really come up, but I guess this needs fixing elsewhere as well.

File: common/buildcraft/transport/plug/FacadeBlockStateInfo.java [hunk 2]
```diff
@@ -36,7 +37,7 @@ public FacadeBlockStateInfo(IBlockState state, ItemStack requiredStack,
         this.isVisible = !requiredStack.isEmpty();
         IBlockAccess access = new SingleBlockAccess(state);
         for (EnumFacing side : EnumFacing.VALUES) {
-            isSideSolid[side.ordinal()] = state.isSideSolid(access, BlockPos.ORIGIN, side);
+            isSideSolid[side.ordinal()] = state.isSideSolid(access, BlockPos.ORIGIN, side) || state.getBlockFaceShape(access, BlockPos.ORIGIN, side) == BlockFaceShape.SOLID;
```
Comment (AlexIIL) [inline common/buildcraft/transport/plug/FacadeBlockStateInfo.java]: What states does this make a difference for?

File: common/buildcraft/transport/plug/PluggableFacade.java (hunk 1 above)
Comment (Managarmr719) [reply common/buildcraft/transport/plug/PluggableFacade.java]: Should a condition be made for it in `FacadeInstance::areAllStatesSolid` instead?

File: common/buildcraft/transport/plug/FacadeBlockStateInfo.java (hunk 2 above)
Comment (AlexIIL) [reply common/buildcraft/transport/plug/FacadeBlockStateInfo.java]: But none of those have solid sides. (Solid -- can place levers, rails, etc on the top or sides).
It might make more sense to add a ````BlockFaceShape```` property.

File: common/buildcraft/transport/plug/PluggableFacade.java (hunk 1 above)
Comment (AlexIIL) [reply common/buildcraft/transport/plug/PluggableFacade.java]: No, I'll fix this bit manually, as it involves changing the API.

**Comment by Managarmr719** [comment]
I made as you recommended, what do you think?

File: common/buildcraft/transport/plug/PluggableFacade.java [hunk 3]
```diff
@@ -108,6 +113,11 @@ public float getExplosionResistance(@Nullable Entity exploder, Explosion explosi
         return states.phasedStates[activeState].stateInfo.state.getBlock().getExplosionResistance(exploder);
     }
 
+    @Override
+    public BlockFaceShape getBlockFaceShape() {
```
Comment (AEnterprise) [inline common/buildcraft/transport/plug/PluggableFacade.java]: travis is failing on this override, you probably added this method in IFacade but that is part of the api (in another repo), could you make a PR there as well for this?

Comment (Managarmr719) [reply common/buildcraft/transport/plug/PluggableFacade.java]: Done.

**Comment by Managarmr719** [comment]
How do I rebuild the PR now that the necessary api changes were made?

**Comment by AEnterprise** [comment]
i've kicked off a rebuild

**Comment by Managarmr719** [comment]
Thanks. 😄

**Comment by Managarmr719** [comment]
It's giving the same error... O_o

**Comment by AlexIIL** [comment]
Force-pull from the main BC API, and add the api submodule to a new commit.

**Comment by AlexIIL** [comment]
Thanks!
